# Dockerfile.dev
FROM node:22.10.0-alpine3.20

# OS Dependencies
RUN apk update && apk add dos2unix && apk add --no-cache bash

# Create app directory.
WORKDIR /app

# Copy Dependencies.
COPY package.json package-lock.json ./

# Usa una caché en un volumen temporal para acelerar la instalación de dependencias
RUN npm set cache /tmp/npm-cache --global
RUN npm set registry https://registry.npmjs.org/

# Install Dependencies.
RUN npm install --legacy-peer-deps

# Bundle app source.
COPY . .

# Generate build
ARG DATABASE_URL
RUN npx prisma generate

# Ports
EXPOSE 4000

CMD [ "npm", "run", "dev" ]